### ISSUE TITLE
Scripts mentioned in OSCW18. 

### ISSUE THREAD

**Issue by kurtulmehtap** [TUDSaT/Comms_Software#3]
I could not pinpoint the (ZeroMQ) to Python scripts that implement the standards for Synchronization and Channel Coding (CCSDS 131.0-B-3, 231.0-B-3), Communications Operation Procedure-1 (CCSDS 232.1-B-2).
They were mentioned in OSCW18. 
 Can you help me locating them?

**Comment by milenko-s** [comment]
Hi,

the ZMQ is not yet used by our scripts. The current flowgraphs will be replaced with new ones that are able to take care of the synchronization and have an ZMQ output.
The development of the COP-1 just started and I hope to be able to present a first version in the upcoming month. When this is done we will connect it with ZMQ to the GNUradio graph.

Best Wishes,
Milenko

**Comment by milenko-s** [comment]
I uploaded a first draft of the FARM-1 to give you an idea where we are trying to get.
